typography_spectrum: 0.59243
color:
  brandStrength: 0.4787234
  lightness: 0.6574468
  saturation: 0.6319149
  rhythmicContrast: 0.3446808
  brandColors:
    - '#ffffff'
    - '#ec7c23'
    - '#f7be43'
    - '#6c6c6c'
    - '#000000'
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25926
analytics:
  twitter: null
  google: null
  facebook: null
name: Foodie On The Go
cta:
  version: null
  bucket: null
  domain: null
navigation:
  - name: Belgian Beers - In Belgium!
    id: b9b4635c-3573-46b8-9daf-f74cb2f53565
    type: content
  - name: 'Musical Pub Crawl, Dublin'
    id: 338fdc58-5481-46a7-95b1-b8c857071f10
    type: content
  - name: 'The Vintage Kitchen, Dublin'
    id: 01c1d4cf-8c2b-46b7-8d21-c532221ccb41
    type: content
  - name: 'Barrio Cantina Food Truck Festival, Antwerp, Belgium'
    id: 22acd5c9-0938-4d97-b1c0-4ecebc87d62a
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Foodie On The Go
purpose: []
