name: Foodie On The Go
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.13895
title: Foodie On The Go
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2425205719191581
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.09285354125313461
purpose: []
