name: foodieonthego
favicon: null
layout_spectrum: 0.2820109867025167
typography_spectrum: 0.13895
title: Foodie On The Go
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2425205719191581
  lightness: 0.36758838477544487
  saturation: 0.9342232525814325
  rhythmicContrast: 0.09285354125313461
purpose: []
